#!/bin/bash
# you need to 
#  1- enable basic auth in the wordpress deployment first. I used this one: https://github.com/WP-API/Basic-Auth
#  2- enable the plugin in wordpress
#  3- create a user that can publish a new post (here chris, password foo)
domain=${MY_DOMAIN:-hpe.org}
content=$(mktemp)
cat <<EOF >${content}
{
  "title": "HPE Nimble and Kasten",
  "content": "${fortune}",
  "status": "publish"
}
EOF
curl \
  --user chris:foo \
  http://wordpress.prod.${domain}/wp-json/wp/v2/posts \
  --data title="HPE Nimble and Kasten" \
  --data status=publish \
  --data content="$(/usr/games/fortune)"

unlink ${content}
#     --header "Accept: application/json" -H "Content-Type: application/json" \
